name: Test Secret

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret Exists
        run: |
          echo "Length: ${#KEY}"
        env:
          KEY: ${{ secrets.EC2_SSH_KEY }}