name: Test SSH Key

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show key header
        run: |
          echo "$KEY" | head -n 3
        env:
          KEY: ${{ secrets.EC2_SSH_KEY }}